blank_issues_enabled: false
contact_links:
  - name: ğŸ— Building on the Sandbox
    url: https://robotology.github.io/icub-gazebo-grasping-sandbox/building-on-sandbox.html
    about: List of works that we know were built on the sandbox.
  - name: ğŸ—£ Discussions and Q&A
    url: https://github.com/robotology/icub-gazebo-grasping-sandbox/discussions
    about: Post questions and discuss ideas on how to design your own solution building on this sandbox.
  - name: ğŸ‘¨ğŸ»â€ğŸ’» Robotology Community
    url: https://github.com/robotology/community/discussions
    about: For general discussions.
